config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end
  get 'articles/index'
  get 'articles/show'
  get 'audience_services/index'
  get 'partner_services/index'
  get 'audiences/index'
  get 'partners/index'
  get 'services/index'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :services, only: [:index]
  resources :audiences, only: [:index]
  resources :partners, only: [:index]
  resources :partner_services, only: [:index]
  resources :audience_services, only: [:index]
  resources :messages, only: [:new, :create]
  resources :articles, only: [:index, :new, :create]
  get '/articles/:title_param', to: 'articles#show', as: 'article'
  get '/articles/:title_param/edit', to: 'articles#edit', as: :edit_article
  patch '/articles/:id', to: "articles#update"
  delete '/articles/:id', to: "articles#destroy"
  get 'about', to: 'pages#about'
  get 'leaders', to: 'pages#leaders'
  get 'companies', to: 'pages#companies'
  get 'privacy-policy', to: 'pages#privacy_policy'
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, uniqueness: true, presence: true
  # validates :photo, presence: true
  validates :article_categories, presence: true
  validates :rich_body, presence: true
  # belongs_to :partner
  belongs_to :user
  has_many :article_categorizations, dependent: :destroy
  has_many :article_categories, through: :article_categorizations
  has_one_attached :photo, service: :cloudinary
  before_create :set_title_param
  before_update :set_title_param
  has_rich_text :rich_body

  protected

  def set_title_param
    self.title_param = self.title.parameterize
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @articles = policy_scope(Article)
    @months = ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"]
  end

  def show
    @article = Article.find_by(title_param: params[:title_param])
    authorize @article
  end

  def new
    @article = Article.new
    authorize @article
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    authorize @article

    if @article.save
      flash[:success] = "Article successfully created"
      redirect_to article_path(title_param: @article.title_param)
      # redirect_to controller: 'article', action: 'show', title_param: @article.title_param
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def edit
    @article = Article.find_by(title_param: params[:title_param])
    authorize @article
  end

  def update
    @article = Article.find(params[:id])
    authorize @article
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(title_param: @article.title_param)
    else
      flash[:error] = "Something went wrong"
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    authorize @article
    if @article.destroy
      flash[:success] = 'Article was successfully deleted.'
      redirect_to articles_path
    else
      flash[:error] = 'Something went wrong'
      redirect_to article_path(title_param: @article.title_param)
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :partner_id, :rich_body, :photo, article_category_ids: [])
  end
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>

  <!-- [...] -->

  <div class="form-inputs">
    <%= f.input :title, label: "Título" %>
    <%= f.input :photo, as: :file, label: "Imagem", input_html: { multiple: false } %>
  </div>

  <div class="form-inputs">
    
    <%= f.association :article_categories,  as: :check_boxes, label: "Categorias", collection: ArticleCategory.order(:name), label_method: :name, value_method: :id %>
  </div>

  <!-- insert these three line of code below -->
  <div class="form-inputs">
    <%= f.rich_text_area :rich_body %>
  </div>

  <div class="form-actions pt-3">
    <%= f.button :submit, f.object.new_record? ? 'Criar Artigo' : 'Atualizar', class: "btn btn-info purple inverted fixwidth" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container pt-3">

  <h2>Editar Artigo</h2>

  <%= render 'form', article: @article %>
  <div class="auth-links">
    <%= link_to "Voltar", :back, class: "btn btn-info gray soft" %>
    <br>
  </div>
</div>

app/views/articles/index.html.erb
<div class="banner--article">
    <div>
        <h1 class="banner__title">Inspire-se</h1>
        <%# <h2 class="banner__subtitle">Escolha</h2> %>
    </div>
</div>
<div class="container text-pic-subban">
    <%# <h1 class="text-pic-subban__title">Para sua Empresa</h1> %>
    <%# <hr class="text-pic-subban__hr"> %>
    <div class="text-pic-subban__text-box-full">
        <p class="text-pic-subban__paragraph">“Ao fazer o que você ama, você inspira e desperta o coração de outros seres.”
        </p>
        <p class="text-pic-subban__paragraph">Satsuki Shibuya</p>
    </div>
</div>
<div class="subbanner--gray">
  <div class="article-wrapper">
    <% @articles.order(created_at: :desc).each do |article| %>
    <div class="flex-article">
      <article class="blog-card">
        <div class="blog-card__background">
          <div class="card__background--wrapper">
            <div class="card__background--main" style="background-image: url(
            <% if article.photo.key.nil?%>
              <%= asset_path( 'article-placeholder-s.jpg' )%>
            <% else %>
              <% begin %>
                <%= cl_image_path article.photo.key %>
              <% rescue  CloudinaryException %>
                <%= asset_path( 'article-placeholder-s.jpg' )%>
              <% end %>
            <% end %>
            );">
              <div class="card__background--layer"></div>
            </div>
          </div>
        </div>
        <div class="blog-card__head">
          <span class="date__box">
            <span class="date__day"> <%= article.created_at.day %> </span>
            <span class="date__month"> <%= @months[article.created_at.month - 1] %></span>
          </span>
        </div>
        <div class="blog-card__info">
          <h5> <%= link_to article.title.truncate_words(10), article_path(article.title_param) %> </h5>
          
          <p>
            <%= link_to "#{article.user.full_name}", about_path(anchor: "#{article.user.first_name.downcase}#{article.user.last_name.downcase}" ), class: "article__p__a" %>
          </p>
          <p> <%= article.rich_body.to_plain_text.truncate_words(9) %></p>
          <%# <a href="#" class="btn btn--with-icon"><i class="btn-icon fa fa-long-arrow-right"></i>Leia Mais</a> %>
        </div>
      </article>
    </div>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container pt-3">

  <h2>Novo Artigo</h2>

  <%= render 'form', article: @article %>
  <div class="auth-links">
    <%= link_to "Voltar", :back, class: "btn btn-info gray soft" %>
    <br>
  </div>
</div>

app/views/articles/show.html.erb
<div class="banner--empty" style="background-image: url(
            <% if @article.photo.key.nil?%>
              <%= asset_path( 'article-placeholder-s.jpg' )%>
            <% else %>
              <% begin %>
                <%= cl_image_path @article.photo.key %>
              <% rescue  CloudinaryException %>
                <%= asset_path( 'article-placeholder-s.jpg' )%>
              <% end %>
            <% end %>
            );">
    <div>
      <h1 class="banner--empty__title"> <%= @article.title %></h1>
      <%# <h2 class="banner__subtitle">Escolha</h2> %>
    </div>
</div>
<div class="article">
  <div class="article__date"> <%= "#{@article.created_at.day}/#{@article.created_at.month}/#{@article.created_at.year}" %></div>
  <div class="article__side-block">
    <div class="article__authors">
      <div class="article__author">
        <%= link_to image_tag("#{@article.user.photo.filename}", width: 200, height: 200, class: "article__avatar"), about_path(anchor: "#{@article.user.first_name.downcase}#{@article.user.last_name.downcase}"), class: "article__avatar", alt:"#{@article.user.full_name}" %>
        <div class="article__author-text">
          <div class="article__author-name"> 
            <%= link_to "#{@article.user.first_name} #{@article.user.last_name}", about_path(anchor: "#{@article.user.first_name.downcase}#{@article.user.last_name.downcase}") %>
          </div>
          <div class="article__author-about"> 
            <%= "#{@article.user.about}"%>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="article__textbox">
    <div class="article__p">
      <%= @article.rich_body %>
    </div>
  </div>
  <div class="auth-links">
    <%= link_to "Artigos", articles_path, class: "btn btn-info gray soft" %>
    <% if policy(@article).edit? %>
      <%= link_to "Editar", edit_article_path(title_param: @article.title_param), class: "btn btn-info gray soft" %>
    <% end %>
    <% if policy(@article).destroy? %>
      <%= link_to "Deletar",
        article_path(@article),
        method: :delete,
        class: "btn btn-info gray soft",
        data: { confirm: "Tem certeza de que quer deletar esse artigo?" } 
      %>
    <% end %>
    <br>
  </div>
</div>