config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  authenticate :user, ->(user) { user.admin? } do
    mount Blazer::Engine, at: "blazer"
  end
  get 'articles/index'
  get 'articles/show'
  get 'audience_services/index'
  get 'partner_services/index'
  get 'audiences/index'
  get 'partners/index'
  get 'services/index'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :services, only: [:index]
  resources :audiences, only: [:index]
  resources :partners, only: [:index]
  resources :partner_services, only: [:index]
  resources :audience_services, only: [:index]
  resources :messages, only: [:new, :create]
  resources :articles, only: [:index, :new, :create]
  get '/articles/:title_param', to: 'articles#show', as: 'article'
  get '/articles/:title_param/edit', to: 'articles#edit', as: :edit_article
  patch '/articles/:id', to: "articles#update"
  delete '/articles/:id', to: "articles#destroy"
  get 'about', to: 'pages#about'
  get 'leaders', to: 'pages#leaders'
  get 'companies', to: 'pages#companies'
  get 'privacy-policy', to: 'pages#privacy_policy'
end

app/views/shared/_contact-modal.html.erb
<div class="modal fade" id="contactUsModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Contate-nos!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <%# <label for="our-email" class="col-form-label">Nosso email:</label> %>
            <input type="hidden" class="form-control" id="our-email" value="contato@discoverthelighthouse.com" readonly>
          </div>
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Seu nome:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="form-group">
            <label for="recipient-email" class="col-form-label">Seu email:</label>
            <input type="text" class="form-control" id="recipient-email">
          </div>
          <div class="form-group">
            <label for="message-text" class="col-form-label">Sua mensagem:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-info purple" data-dismiss="modal">Fechar</button>
        <%= link_to "Enviar", create_message_path, class='btn btn-info purple inverted'%>
        <%# <button type="button" class="btn btn-info purple">Enviar</button> %>
        
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="jumbotron container-footer on-hover">
  <div class="container">
    <footer>
        <div class="row d-md-none">
            <div class="col-xs-6 col-sm-6 border-right">
              <p class="text-center">
                <%= link_to services_path do %>Serviços<% end %>
              </p>
            </div>
            <div class="col-xs-6 col-sm-6 border-right">
                <p class="text-center">
                  <%= link_to leaders_path do %>Você<% end %>
                </p>
            </div>
            <div class="col-xs-6 col-sm-6 border-right">
                <p class="text-center">
                  <%= link_to companies_path do %>Empresas<% end %>
                </p>
            </div>
            <div class="col-xs-6 col-sm-6 border-right">
                <p class="text-center">
                  <%= link_to articles_path do %>Artigos<% end %>
                </p>
            </div>
            <div class="col-xs-6 col-sm-6 border-right">
                <p class="text-center">
                  <%= link_to about_path do %>Nós<% end %>
                </p>
            </div>
            <div class="col-xs-6 col-sm-6 border-right">
                <p class="text-center">
                  <a href="mailto:contato@discoverthelighthouse.com" target="_blank">
                    Contate-nos
                 </a>
                </p>
            </div>
        </div>

        <div class="row d-none d-md-block">
            <p class="text-center">
                <%= link_to services_path do %>Serviços<% end %>
                &nbsp;&nbsp;|&nbsp;&nbsp;
                <%= link_to leaders_path do %>Você<% end %>
                &nbsp;&nbsp;|&nbsp;&nbsp;
                <%= link_to companies_path do %>Empresas<% end %>
                &nbsp;&nbsp;|&nbsp;&nbsp;
                <%= link_to articles_path do %>Artigos<% end %>
                &nbsp;&nbsp;|&nbsp;&nbsp;
                <%= link_to about_path do %>Nós<% end %>
                &nbsp;&nbsp;|&nbsp;&nbsp;
                <a href="mailto:contato@discoverthelighthouse.com" target="_blank">
                  Contate-nos
                </a>
            </p>
        </div>

        <div class="row" style="margin-top:60px; justify-content:center">
            <div>
                <ul class="list-inline">
                    <li>
                      <a href="https://www.facebook.com/thelighthouse.carreira/" title="Nosso Facebook" target="_blank">
                          <i class="fab fa-facebook-square fa-lg"></i>
                      </a>
                    </li>
                    &nbsp;&nbsp;
                    <li>
                      <a href="https://www.instagram.com/thelighthouse_consultoria" title="Nosso Instagram" target="_blank">
                          <i class="fab fa-instagram-square fa-lg"></i>
                      </a>
                    </li>
                    &nbsp;&nbsp;
                    <li>
                      <a href="https://www.linkedin.com/company/thelighthouse-consulting" title="Nosso Linkedin" target="_blank">
                          <i class="fab fa-linkedin fa-lg"></i>
                      </a>
                    </li>
                    &nbsp;&nbsp;
                    <li>
                      <a href="mailto:contato@discoverthelighthouse.com" title="Nosso Email" target="_blank">
                          <i class="far fa-envelope fa-lg"></i>
                      </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="row" style="margin-top:40px; justify-content:center">
            <div>
              <%= link_to "Política de Privacidade", privacy_policy_path  %>
            </div>
        </div>
        <div class="row" style="margin-top:40px; justify-content:center">
            <div>
              <p class="text-center">
                ©The Lighthouse. Todos os direitos reservados 2021.
              </p>
            </div>
        </div>
	</footer>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-tlh">
  <%= link_to "/", class: "navbar-brand logo-text" do %>
    <%= image_tag "avatar-logo.jpg" %>

    <%# THE LIGHTHOUSE %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div><%= render "messages/new", message: Message.new %></div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
       <li class="nav-item">
          <%= link_to "Serviços", services_path, class: current_class?(services_path) %>
        <hr></li>
        <li class="nav-item">
          <%= link_to "Para Você", leaders_path, class: current_class?(leaders_path) %>
        <hr></li>
        <li class="nav-item">
          <%= link_to "Para Empresas", companies_path, class: current_class?(companies_path) %>
        <hr></li>
        <li class="nav-item">
          <%= link_to "Artigos", articles_path, class: current_class?(articles_path) %>
        <hr></li>
        <li class="nav-item">
          <%= link_to "Sobre Nós", about_path, class: current_class?(about_path) %>
        <hr></li>
        <li class="nav-item">
          <%#= link_to '#contactUsModal', 'data-toggle' => "modal" do %>
            <%# Contate-nos
          <% end %>
          <%#= link_to "Contate-nos", new_message_path, class: 'btn btn-info purple inverted'%>
          <%= link_to "Contato", new_message_path, class: current_class?(new_message_path), data: { toggle: 'modal', target: '#contactUsModal'}%>
        <hr></li>
        <li class="nav-item dropdown">
          <% begin %>
            <% if !current_user.photo.key.nil?  %>
              <%= cl_image_tag(current_user.photo.key, secure: true, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <% else %>
              <%= image_tag "empty-profile.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
          <% rescue CloudinaryException %>
            <%= image_tag "empty-profile.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% if policy(Article).create? %>
            <%= link_to "Criar Artigo", new_article_path, class: "dropdown-item" %>
          <% end %>
            <%#= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
          <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
        <li class="nav-item">
          <%= link_to "Serviços", services_path, class: current_class?(services_path) %>
        <hr></li>
        <li class="nav-item">
          <%= link_to "Para Você", leaders_path, class: current_class?(leaders_path) %>
        <hr></li>
        <li class="nav-item">
          <%= link_to "Para Empresas", companies_path, class: current_class?(companies_path) %>
        <hr></li>
        <li class="nav-item">
          <%= link_to "Artigos", articles_path, class: current_class?(articles_path) %>
        <hr></li>
        <li class="nav-item">
          <%= link_to "Sobre Nós", about_path, class: current_class?(about_path) %>
        <hr></li>
        <li class="nav-item">
          <%#= link_to '#contactUsModal', 'data-toggle' => "modal" do %>
            <%# Contate-nos
          <% end %>
          <%#= link_to "Contate-nos", new_message_path, class: 'btn btn-info purple inverted'%>
          <%= link_to "Contato", new_message_path, class: current_class?(new_message_path), data: { toggle: 'modal', target: '#contactUsModal'}%>
        <hr></li>

        
        
        <li class="nav-item dropdown">
          <%#= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_service-card.html.erb
<div class="service-card">
    <div class="meta">
        <div class="photo" style="background-image: url(https://storage.googleapis.com/chydlx/codepen/blog-cards/image-1.jpg)"></div>
        <%# <ul class="details">
        <li class="author"><a href="#">John Doe</a></li>
        <li class="date">Aug. 24, 2015</li>
        </ul> %>
    </div>
    <div class="description">
        <h1>Learning to Code</h1>
        <h2>Opening a door to the future</h2>
        <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad eum dolorum architecto obcaecati enim dicta praesentium, quam nobis! Neque ad aliquam facilis numquam. Veritatis, sit.</p>
        <p class="read-more">
        <a href="#">Read More</a>
        </p>
    </div>
</div>